name: Prism
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.6.1+58

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  cached_network_image: ^2.2.0+1
  carousel_slider: ^2.2.1
  cloud_firestore: ^0.13.5
  confetti: ^0.5.4+1
  data_connection_checker: ^0.3.4
  device_info: ^0.4.2+7
  extended_image: ^0.9.0
  firebase_admob: ^0.9.3+4
  firebase_analytics: ^5.0.16
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  firebase_dynamic_links: ^0.5.1
  firebase_messaging: ^6.0.16
  firebase_remote_config: ^0.3.1+1
  flare_flutter: ^2.0.5
  flare_splash_screen: ^3.0.1
  flutter_displaymode: ^0.1.1
  flutter_image_compress: ^0.7.0
  flutter_svg: ^0.19.0
  fluttertoast: ^4.0.1
  gallery_saver: ^2.0.1
  github: ^6.2.2
  google_sign_in: ^4.4.4
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+1
  image_editor: ^0.7.1
  image_picker: ^0.6.7+4
  in_app_purchase: ^0.3.4+1
  in_app_update: ^1.1.13
  palette_generator: ^0.2.2
  path_provider: ^1.6.11
  permission_handler: ^5.0.1+1
  photo_view: ^0.9.2
  photofilters: ^2.0.1
  provider: ^4.1.3
  purchases_flutter: ^1.2.1
  rate_my_app: ^0.7.2
  screenshot: ^0.2.0
  share: ^0.6.4
  sliding_up_panel: ^1.0.2
  url_launcher: ^5.4.5

dependency_overrides:
  image: ^2.1.12
  analyzer: 0.40.4
dev_dependencies:
  build_runner: 1.10.3
  flutter_launcher_icons: ^0.8.1
  hive_generator: 0.8.1
  lint: 1.2.0

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/icon/ic_launcher_xxxhdpi.png
  image_path_ios: assets/icon/ios.png
  adaptive_icon_background: assets/icon/ic_background.png
  adaptive_icon_foreground: assets/icon/ic_foreground.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
          weight: 500
        - asset: assets/fonts/Proxima Nova Thin.otf
          weight: 300
        - asset: assets/fonts/Proxima Nova Thin.otf
          weight: 400
        - asset: assets/fonts/Proxima Nova Bold.otf
          weight: 600
        - asset: assets/fonts/Proxima Nova Extrabold.otf
          weight: 700
        - asset: assets/fonts/Proxima Nova Black.otf
          weight: 800
        - asset: assets/fonts/Proxima Nova Black.otf
          weight: 900

    - family: JamIcons
      fonts:
        - asset: assets/fonts/JamIcons.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
